// <auto-generated />
using System;
using BusinessManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224231214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_client_email");

                    b.HasIndex("FullName")
                        .HasDatabaseName("idx_client_fullname");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("idx_client_phone");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("idx_equipment_serial");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_equipment_type");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.PartCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("DefaultUnitPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_partcatalog_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_partcatalog_name");

                    b.ToTable("PartCatalogItems");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_user_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_user_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_user_role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.WarrantyClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginalWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimWorkOrderId")
                        .HasDatabaseName("idx_warrantyclaim_claim");

                    b.HasIndex("OriginalWorkOrderId")
                        .HasDatabaseName("idx_warrantyclaim_original");

                    b.ToTable("WarrantyClaims");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedMechanicUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeliveredAtLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("QuoteRejectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuoteRejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuoteRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestedWorkDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WarrantyDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WarrantyOriginalWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMechanicUserId")
                        .HasDatabaseName("idx_workorder_mechanicid");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("idx_workorder_clientid");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("idx_workorder_createdat");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_workorder_status");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_workorder_number");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.WarrantyClaim", b =>
                {
                    b.HasOne("BusinessManagementSystem.Domain.Entities.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("ClaimWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warrantyclaim_claim");

                    b.HasOne("BusinessManagementSystem.Domain.Entities.WorkOrder", null)
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("OriginalWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_warrantyclaim_original");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("BusinessManagementSystem.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workorder_client");

                    b.HasOne("BusinessManagementSystem.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workorder_equipment");

                    b.OwnsMany("BusinessManagementSystem.Domain.Entities.WorkOrderAccessory", "Accessories", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<bool>("IsPresent")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<DateTime>("RegisteredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkOrderId")
                                .HasDatabaseName("idx_accessory_workorderid");

                            b1.ToTable("WorkOrderAccessories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("BusinessManagementSystem.Domain.Entities.WorkOrderDiagnosis", "Diagnosis", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Findings")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MechanicUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("RecommendedWork")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrderDiagnosis", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsMany("BusinessManagementSystem.Domain.Entities.WorkOrderPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("CatalogItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PartName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("RegisteredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal?>("UnitPrice")
                                .HasPrecision(15, 2)
                                .HasColumnType("numeric(15,2)");

                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkOrderId")
                                .HasDatabaseName("idx_part_workorderid");

                            b1.ToTable("WorkOrderParts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("BusinessManagementSystem.Domain.Entities.WorkOrderQuote", "Quote", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CreatedByUserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("LaborCost")
                                .HasPrecision(15, 2)
                                .HasColumnType("numeric(15,2)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<decimal>("PartsTotal")
                                .HasPrecision(15, 2)
                                .HasColumnType("numeric(15,2)");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrderQuote", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.OwnsOne("BusinessManagementSystem.Domain.Entities.WorkOrderServiceReport", "ServiceReport", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MechanicUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("Recommendations")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("WorkPerformed")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("WorkOrderId");

                            b1.ToTable("WorkOrderServiceReport", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderId");
                        });

                    b.Navigation("Accessories");

                    b.Navigation("Client");

                    b.Navigation("Diagnosis");

                    b.Navigation("Equipment");

                    b.Navigation("Parts");

                    b.Navigation("Quote");

                    b.Navigation("ServiceReport");
                });

            modelBuilder.Entity("BusinessManagementSystem.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("WarrantyClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
